###############################################################################
# TMUX config aliz64
###############################################################################

# Use Ctrl-w as prefix
unbind C-b
set -g prefix C-w
bind-key C-w send-prefix

# Use the default shell within TMUX panes/windows
set-option -g default-shell $SHELL

set-option -g history-limit 10000

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Reload this file on r
bind r source-file ~/.tmux.conf

# set escape time to 0
set -s escape-time 0

# prevent tmux from reneaming windows
set-option -g allow-rename off

# colors for status bar
set -g status-bg colour233
set -g status-fg green

# Set to use 256 colors
set -g default-terminal "screen-256color"

# Set mouse mode
# This also enables copy-on-select (copy is done to tmux buffer)
set -g mouse on

# Fast pane switching
unbind -n M-Left   # select-pane -L
unbind -n M-Right  # select-pane -R
unbind -n M-Up     # select-pane -U
unbind -n M-Down   # select-pane -D
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

set-option -s set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind P paste-buffer


###############################################################################
# NOT WORKING / OLD TMUX VERSIONS
###############################################################################

# Copy goes to system clipboard too
#bind -t vi-copy y copy-pipe "xclip -sel clip -i"

# vim style copy paste
#bind P paste-buffer
#bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
#bind-key -T copy-mode-vi 'y' send-keys -X copy-selection
#bind-key -T copy-mode-vi 'r' send-keys -X rectangle-toggleS

#setw -g mode-mouse on
#set -g mouse-select-window on
#set -g mouse-select-pane on
#set -g mouse-resize-pane off
#set -g mouse-utf on

###############################################################################
